version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled 
    depends_on:
      - php-fpm
    restart:
      always
    networks:
      - app_network

  php-fpm:
    build: ./build/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./public:/var/www/html/public
    networks:
      - app_network

  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: menu_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --init-file /data/application/init.sql
    volumes:
      - ./db:/var/lib/mysql
      - ./db_init.sql:/data/application/init.sql
    networks:
      - app_network
    restart:
      always

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app_network
    
networks:
  app_network:
